name: Spring Boot CICD

# Trigger the workflow on push and pull_request events
on:
  push:
    branches:
      - main  # Trigger on changes to the main branch

# Define the jobs in the workflow
jobs:
  build:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner

    steps:
      # Step 1: Check out the code from the GitHub repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Java (OpenJDK 11) on the runner
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'

      # Step 3: Build the project using Maven
      - name: Build with Maven
        run: mvn clean install -DskipTests=false  # Skips tests during build (can adjust based on needs)

      # Step 4: Run unit tests
      #- name: Run tests
      #  run: mvn test  # Run the tests using Maven

      # Optional Step 5: Build a Docker image (if you want to create a Docker image)
      - name: Build Docker image
        run: |
          docker build -t spring-boot-app .
          docker images  # List images for debugging
